backend:
  name: git-gateway
  branch: main

site_url: https://dainty-haupia-5c5004.netlify.app
display_url: https://dainty-haupia-5c5004.netlify.app

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Cakes", value: "cakes" }
          - { label: "Pastries", value: "pastries" }
          - { label: "Seasonal", value: "seasonal" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Photo", name: "image", widget: "image", required: false }
      - { label: "Order", name: "order", widget: "number", default: 99 }